name: enterprise-suite

services:
  inventory-db:
    image: mongo:latest
    container_name: inventory-mongo
    ports:
      - "27017:27017"
    volumes:
      - inventory-data:/data/db

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: enterprise # NOT FOR PRODUCTION USE
      RABBITMQ_DEFAULT_PASS: enterprise_dev_pw # NOT FOR PRODUCTION USE
    ports:
      - "5672:5672" # AMQP protocol port (used byservices)
      - "15672:15672" # Management UI - browser dashboard
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  sales-db:
    image: postgres:latest
    container_name: sales-postgres
    environment:
      POSTGRES_USER: sales_user
      POSTGRES_PASSWORD: sales_pw
      POSTGRES_DB: SalesDb
    ports:
      - "5433:5432"
    volumes:
      - sales-data:/var/lib/postgresql

volumes:
  inventory-data:
  rabbitmq-data:
  sales-data: