spring.application.name=finance-service

spring.datasource.url=jdbc:postgresql://localhost:5434/FinanceDb
spring.datasource.username=finance_user
spring.datasource.password=finance_pw

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=enterprise
spring.rabbitmq.password=enterprise_dev_pw

# Messages failing will be rejected, not requeued
spring.rabbitmq.listener.simple.default-requeue-rejected=false